name: Node CI

on:
  push:
    branches: '*'
  pull_request:
    branches : '*'
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@2
    - name: Use Node.js 18
      uses: actions/setup-node@3
      with:
        node-version: '18'
    - name: npm install and test
      run: |
        npm install
        npm test
